services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped

    environment:
      TZ: "Europe/Amsterdam"
      DISABLE_IPV6: 'true'

    network_mode: bridge

    ports:
      - "81:81"
      - "443:443"
      - "4443:4443"

    volumes:
      - /home/portainer/docker/npm/data:/data
      - /home/portainer/docker/npm/letsencrypt:/etc/letsencrypt