services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped

    environment:
      TZ: "Europe/Amsterdam"
      DISABLE_IPV6: 'true'

    networks:
      - npm-bridge
      - npm-proxy

    ports:
      - "80:80"
      - "81:81"
      - "443:443"

    volumes:
      - /opt/appdata/npm/data:/data
      - /opt/appdata/npm/letsencrypt:/etc/letsencrypt
networks:
  npm-bridge:
    driver: bridge
  npm-proxy:
    name: npm-proxy